services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gateway-payment-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PaymentGateway@123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_global_data:/var/opt/mssql

volumes:
  mssql_global_data: