services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: gateway-payment-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PaymentGateway@123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_global_data:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: paymentgateway_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mssql_global_data: